from pathlib import Path
import sys
import json

ROOT_DIR = Path(__file__).resolve().parents[2]
sys.path.append(str(ROOT_DIR))

POLICY_CASES_PATH = ROOT_DIR / "data" / "processed" / "ravenledger_policy_cases.json"
REPORTS_DIR = ROOT_DIR / "data" / "processed" / "reports"


def load_policy_cases() -> list[dict]:
    if not POLICY_CASES_PATH.exists():
        raise FileNotFoundError(
            f"Missing file: {POLICY_CASES_PATH}. Run policy_engine.py first."
        )

    with open(POLICY_CASES_PATH, "r", encoding="utf-8") as file:
        return json.load(file)


def bullet_list(items) -> str:
    if not items:
        return "- None recorded"

    return "\n".join(f"- {item}" for item in items)


def build_splunk_evidence_section(case: dict) -> str:
    evidence = case.get("splunk_evidence_sample", [])

    if not evidence:
        return "- No Splunk evidence attached."

    lines = []

    for item in evidence[:5]:
        time_value = item.get("time", "")
        host = item.get("host", "")
        sourcetype = item.get("sourcetype", "")
        source = item.get("source", "")

        lines.append(
            f"- `{time_value}` | host=`{host}` | sourcetype=`{sourcetype}` | source=`{source}`"
        )

    return "\n".join(lines)


def generate_markdown_report(case: dict) -> str:
    spl_query = case.get("splunk_spl", "")

    report = f"""# RavenLedger Audit Report

## 1. Incident Summary

**Correlation Case ID:** {case.get("correlation_case_id", "")}  
**Business Case ID:** {case.get("business_case_id", "")}  
**Invoice ID:** {case.get("invoice_id", "")}  
**Supplier ID:** {case.get("supplier_id", "")}  
**Department:** {case.get("department_id", "")}  
**Invoice Amount:** {case.get("invoice_amount", "")} {case.get("currency", "")}  

**Combined Risk Score:** {case.get("combined_risk_score", "")}/100  
**Severity:** {case.get("severity", "")}  
**Human Approval Required:** {case.get("human_approval_required", "")}  

---

## 2. Business Risk Evidence

**Business Risk Score:** {case.get("business_risk_score", "")}  
**Business Severity:** {case.get("business_severity", "")}  

**Business Reasons:**
{bullet_list(case.get("business_reasons", []))}

**Business Recommended Step:**  
{case.get("business_recommended_next_step", "")}

---

## 3. Insider Risk Evidence

**Insider User:** {case.get("insider_user", "")}  
**Insider Case ID:** {case.get("insider_case_id", "")}  
**Insider Risk Score:** {case.get("insider_risk_score", "")}  
**Insider Severity:** {case.get("insider_severity", "")}  

**Insider Signals:**
{bullet_list(case.get("insider_signals", []))}

---

## 4. Splunk Evidence

**Splunk Evidence Package:** {case.get("splunk_evidence_package_id", "")}  
**Query Name:** {case.get("splunk_query_name", "")}  
**Evidence Count:** {case.get("splunk_evidence_count", "")}  

**SPL Used:**

```spl
{spl_query}
```

**Sample Evidence:**
{build_splunk_evidence_section(case)}

---

## 5. Policy Violations

{bullet_list(case.get("policy_violations", []))}

---

## 6. Controls Triggered

{bullet_list(case.get("controls_triggered", []))}

---

## 7. Escalation Targets

{bullet_list(case.get("escalation_targets", []))}

---

## 8. Final Recommended Action

{case.get("final_recommended_action", "")}

---

## 9. Correlation Summary

{case.get("correlation_summary", "")}

---

## 10. Audit Note

This report is generated by RavenLedger's agentic investigation pipeline.

The result is an investigation-priority decision, not a final legal or disciplinary conclusion.

Human review is required before any payment block, employee action, or compliance escalation.
"""

    return report


def save_report(case: dict) -> Path:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    case_id = case.get("correlation_case_id", "unknown-case")
    report_path = REPORTS_DIR / f"{case_id}.md"

    report = generate_markdown_report(case)

    with open(report_path, "w", encoding="utf-8") as file:
        file.write(report)

    return report_path


def generate_reports(limit: int | None = None) -> list[Path]:
    cases = load_policy_cases()

    if limit is not None:
        cases = cases[:limit]

    report_paths = []

    for case in cases:
        path = save_report(case)
        report_paths.append(path)

    return report_paths


if __name__ == "__main__":
    report_paths = generate_reports(limit=10)

    print("RavenLedger Audit Report Engine")
    print("=" * 70)

    for path in report_paths:
        print("Generated:", path)

    print("\nTotal reports generated:", len(report_paths))